import {
  Sun,
  Moon,
  Monitor,
  Coffee,
  Palette,
  Heart,
  Leaf,
  Ghost,
  TreePine,
  Flower,
  Star,
  Sparkles,
  Skull,
  Droplet,
  IceCream,
  Shield,
  Bug,
  Flame,
  Code,
  Paintbrush,
  Snowflake,
  Sunset,
  Eye,
} from "lucide-react";

export const themeIconMap = {
  light: Sun,
  dark: Moon,
  system: Monitor,
  cupcake: IceCream,
  bumblebee: Droplet,
  emerald: Leaf,
  corporate: Shield,
  synthwave: Star,
  retro: Palette,
  cyberpunk: Bug,
  valentine: Heart,
  halloween: Ghost,
  garden: Flower,
  forest: TreePine,
  aqua: Droplet,
  lofi: Coffee,
  pastel: Paintbrush,
  fantasy: Sparkles,
  wireframe: Code,
  black: Moon,
  luxury: Star,
  dracula: Skull,
  cmyk: Palette,
  autumn: Flame,
  business: Monitor,
  acid: Bug,
  lemonade: IceCream,
  night: Moon,
  coffee: Coffee,
  winter: Snowflake,
  dim: Eye,
  nord: Snowflake,
  sunset: Sunset,
};
